SLTP_TYPE_ORDER=1
SLTP_TYPE_POS=0

SLTP_STATUS_NONE=0
SLTP_STATUS_READY=1
SLTP_STATUS_FINISH=2

ORDER_TYPE_MARKET=0
ORDER_TYPE_LIMIT=1

TDMODE_ISOLATED=0
TDMODE_CROSS=1
TDMODE_CASH=2
TDMODE_SPOT_ISOLOATED=3

ORDER_STATUS_LIVE=0
ORDER_STATUS_FILLED=1
ORDER_STATUS_PARTIALLY_FILLED=2
ORDER_STATUS_NULL=-1

ORDER_FROM_WEB='web'
ORDER_FROM_HUOXING='huoxing'
ORDER_FROM_TREND='qushi'